import {test,expect,Page,BrowserContext} from '@playwright/test';
import {readFileSync,mkdirSync} from 'fs';
import {randomUUID} from 'crypto';
const credentials=JSON.parse(readFileSync('.local/credentials.json','utf8'));
async function login(page:Page,account:string){const user=credentials.users[account];await page.goto('/');await page.locator('button:has-text("Sign in to your workspace")').click();await page.fill('#username',user.username);await page.fill('#password',user.password);await page.click('#kc-login');await expect(page.locator('h1')).toHaveText('Approval inbox')}
async function create(page:Page,customer:string){await page.locator('button:has-text("New request")').click();await page.locator('label:has-text("Customer name") input').fill(customer);const [response]=await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/requests')&&r.request().method()==='POST'),page.locator('button:has-text("Submit for review")').click()]);expect(response.status()).toBe(202);const {id}=await response.json();await expect(page.locator('#request-title')).toHaveText(customer);return id}
async function approve(page:Page,customer:string,note:string){await page.locator('.queue-item').filter({hasText:customer}).click();await expect(page.locator('#request-title')).toHaveText(customer);await page.locator('label:has-text("Decision note") textarea').fill(note);await page.locator('button:text-is("Approve request")').click();await expect(page.locator('.review .notice')).toContainText('Decision recorded')}
test('requester and both reviewers complete a durable onboarding journey',async({browser,page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await login(page,'requester');const customer='Browser Northstar '+randomUUID().slice(0,8);await create(page,customer);await expect(page.locator('button:text-is("Approve request")')).toHaveCount(0);
 const contexts:BrowserContext[]=[];try{
  for(const account of ['security','commercial']){const context=await browser.newContext({baseURL:'http://localhost:4900'});contexts.push(context);const reviewer=await context.newPage();await login(reviewer,account);await approve(reviewer,customer,account+' evidence verified')}
  await expect(page.locator('.detail .badge')).toHaveText('Approved');await expect(page.locator('.queue-item').filter({hasText:customer}).locator('.badge')).toHaveText('approved');await expect(page.locator('.timeline')).toContainText('Service Activated');mkdirSync('artifacts',{recursive:true});await page.screenshot({path:'artifacts/switchboard-desktop.png',fullPage:true});expect(errors).toEqual([]);
 }finally{for(const context of contexts)await context.close()}
});
test('a lost browser request preserves its retry key and cancellation remains explicit',async({page})=>{
 await login(page,'requester');await page.locator('button:has-text("New request")').click();await page.locator('label:has-text("Customer name") input').fill('Retry customer '+randomUUID().slice(0,8));let firstKey='';
 await page.route('**/api/requests',async route=>{if(route.request().method()==='POST'){firstKey=route.request().headers()['idempotency-key'];await route.abort('failed')}else await route.continue()});await page.locator('button:has-text("Submit for review")').click();await expect(page.locator('.error')).toContainText('Connection interrupted');await expect(page.locator('button:text-is("Retry submission")')).toBeVisible();await page.unroute('**/api/requests');
 const [response]=await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/requests')&&r.request().method()==='POST'),page.locator('button:text-is("Retry submission")').click()]);expect(response.request().headers()['idempotency-key']).toBe(firstKey);await expect(page.locator('#request-title')).toBeVisible();
 await page.locator('button:text-is("Cancel this request")').click();await expect(page.locator('button:text-is("Keep request")')).toBeVisible();await page.locator('button:text-is("Confirm cancellation")').click();await expect(page.locator('.detail .badge')).toHaveText('Cancelled');
});
test('narrow layouts preserve keyboard navigation and logout clears pending state',async({page})=>{
 await page.setViewportSize({width:390,height:844});await login(page,'requester');await page.locator('button:has-text("New request")').click();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'artifacts/switchboard-mobile.png',fullPage:true});await page.evaluate(()=>sessionStorage.setItem('switchboard.intent.test','test'));await page.locator('button:text-is("Sign out")').click();await expect(page.locator('button:has-text("Sign in to your workspace")')).toBeVisible();expect(await page.evaluate(()=>Object.keys(sessionStorage).some(key=>key.startsWith('switchboard.intent.')))).toBe(false);
});
