import React,{useEffect,useState} from 'react';
import {Actor,Snapshot,api} from './api';
import {Review} from './Review';
import {Cancel} from './Cancel';
const title=(value:string)=>value.split('_').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');
export function Detail({id,actor,refresh}:{id:string;actor:Actor;refresh:number}){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[error,setError]=useState('');
 useEffect(()=>{setSnapshot(null);const controller=new AbortController();let active=true;async function load(){try{const value=await api<Snapshot>('/requests/'+id,{signal:controller.signal});if(active){setSnapshot(value);setError('')}}catch(e){if(active)setError((e as Error).message)}}load();const timer=setInterval(load,3000);return()=>{active=false;controller.abort();clearInterval(timer)}},[id,refresh]);
 if(!snapshot)return <section className="detail" aria-live="polite">{error?<p className="error" role="alert">{error}</p>:<p>Loading request…</p>}</section>;
 const s=snapshot;
 return <section className="detail" aria-labelledby="request-title"><div className="detail-top"><p className="eyebrow">REQUEST {s.request.requestId.slice(0,8)}</p><span className={'badge '+s.status}>{title(s.status)}</span></div><h2 id="request-title">{s.request.customer}</h2>{error&&<p className="error" role="alert">{error} The last confirmed state is shown below.</p>}<dl className="details-grid"><div><dt>Plan</dt><dd>{title(s.request.plan)}</dd></div><div><dt>Seats</dt><dd>{s.request.seats}</dd></div><div><dt>Review deadline</dt><dd>{new Date(s.deadline).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</dd></div></dl><ol className="steps" aria-label="Approval progress">{[...s.stages,'activation'].map((stage,i)=><li key={stage} className={i<s.stageIndex||s.status==='approved'?'done':s.status==='pending'&&i===s.stageIndex?'current':''}><span className="step-dot">{i<s.stageIndex||s.status==='approved'?'✓':i+1}</span><strong>{title(stage)}</strong></li>)}</ol>{s.reminded&&s.status==='pending'&&<p className="notice">A review reminder has been recorded. The deadline remains unchanged.</p>}{s.status==='compensation_failed'&&<div className="operator" role="status"><strong>Operator follow-up required</strong><p>Automatic recovery could not confirm every cleanup operation. Review the runbook before retrying provider actions.</p></div>}<Review key={id} snapshot={s} actor={actor}/><Cancel key={id+'-cancel'} snapshot={s} actor={actor}/><h3>Decision history</h3><ol className="timeline">{s.audit.slice().reverse().map(event=><li key={event.sequence}><strong>{title(event.event)}{event.stage?' · '+title(event.stage):''}</strong><time dateTime={new Date(event.at).toISOString()}>{new Date(event.at).toLocaleString()}</time>{event.detail&&<p>{event.detail}</p>}</li>)}</ol></section>
}
