import React,{useState} from 'react';
import {Actor,Input,api} from './api';
import {PendingIntent,intentKey,readIntent,saveIntent} from './intent';
export function NewRequest({actor,onCreated,onBack}:{actor:Actor;onCreated:(id:string)=>void;onBack:()=>void}){
 const key=intentKey(actor.tenantId,actor.id),stored=readIntent(sessionStorage,key),initial=stored?.kind==='request'?stored:null;
 const [intent,setIntent]=useState<PendingIntent|null>(initial),[input,setInput]=useState<Input>((initial?.payload as Input)||{customer:'',plan:'standard',seats:5}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const pending=intent||{kind:'request' as const,id:crypto.randomUUID(),payload:{...input,customer:input.customer.trim()}};saveIntent(sessionStorage,key,pending);setIntent(pending);const result=await api<{id:string}>('/requests',{method:'POST',body:pending.payload,key:pending.id});sessionStorage.removeItem(key);onCreated(result.id)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="form-panel" aria-labelledby="new-request-title"><button className="text-button" onClick={onBack}>← Back to inbox</button><h2 id="new-request-title">Start customer onboarding</h2><p className="quiet">Security and commercial reviewers will approve the request before service activation.</p>{intent&&<p className="notice" role="status">A submission is awaiting confirmation. Retrying uses the same request identity.</p>}{error&&<p className="error" role="alert">{error}</p>}<form onSubmit={submit}><label className="field">Customer name<input required maxLength={120} autoComplete="organization" value={input.customer} disabled={!!intent||busy} onChange={e=>setInput({...input,customer:e.target.value})}/></label><div className="form-row"><label className="field">Plan<select value={input.plan} disabled={!!intent||busy} onChange={e=>setInput({...input,plan:e.target.value as Input['plan']})}><option value="standard">Standard</option><option value="enterprise">Enterprise</option></select></label><label className="field">Seats<input type="number" min={1} max={1000} step={1} required value={input.seats} disabled={!!intent||busy} onChange={e=>setInput({...input,seats:Number(e.target.value)})}/><small>Between 1 and 1,000 seats.</small></label></div><button className="primary" type="submit" disabled={busy}>{busy?'Submitting…':intent?'Retry submission':'Submit for review →'}</button></form></section>
}
