import React,{useEffect,useState} from 'react';
import {Actor,Entry,api} from './api';
import {needsAttention} from './attention';
export function Queue({actor,selected,onSelect,refresh}:{actor:Actor;selected:string|null;onSelect:(id:string)=>void;refresh:number}){
 const [items,setItems]=useState<Entry[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 async function load(next?:string,signal?:AbortSignal){setBusy(true);try{const data=await api<{items:Entry[];nextCursor:string|null}>('/requests?limit=20'+(next?'&cursor='+encodeURIComponent(next):''),{signal});setItems(previous=>next?[...previous,...data.items.filter(x=>!previous.some(p=>p.id===x.id))]:data.items);setCursor(data.nextCursor);setError('')}catch(e){if(!signal?.aborted)setError((e as Error).message)}finally{if(!signal?.aborted)setBusy(false)}}
 useEffect(()=>{const controller=new AbortController();load(undefined,controller.signal);return()=>controller.abort()},[refresh]);
 const visible=items.filter(x=>x.input.customer.toLowerCase().includes(query.toLowerCase())).filter(x=>filter==='all'||(filter==='review'?x.snapshot?.status==='pending'&&actor.roles.includes(x.snapshot.stage+'-reviewer')&&x.snapshot.request.requesterId!==actor.id:needsAttention(x)));
 return <section aria-label="Request queue"><div className="toolbar"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')} aria-pressed={filter==='all'}>All</button><button className={filter==='review'?'selected':''} onClick={()=>setFilter('review')} aria-pressed={filter==='review'}>My reviews</button><button className={filter==='attention'?'selected':''} onClick={()=>setFilter('attention')} aria-pressed={filter==='attention'}>Attention</button><label className="sr-only" htmlFor="customer-search">Search loaded customer requests</label><input id="customer-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a customer…"/></div>{error&&<p role="alert" className="error">{error} <button onClick={()=>load()}>Retry queue</button></p>}<div className="queue" aria-busy={busy}>{visible.map(item=><button key={item.id} className={'queue-item'+(selected===item.id?' active':'')} onClick={()=>onSelect(item.id)} aria-pressed={selected===item.id}><strong>{item.input.customer}</strong><div className="queue-meta"><span>{item.input.plan} · {item.input.seats} seats</span><span className={'badge '+(item.snapshot?.status||'')}>{item.stateUnavailable?'State unavailable':item.snapshot?.status||'Starting'}</span></div><div className="queue-meta"><span>{new Date(item.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><span>{item.id.slice(0,8)}</span></div></button>)}{!busy&&!visible.length&&<div className="empty"><h2>No requests here yet</h2><p>{filter==='review'?'You have no pending reviews in the loaded requests.':'Create a request or adjust your search.'}</p></div>}</div>{busy&&<p role="status" className="quiet">Loading requests…</p>}{cursor&&<button disabled={busy} onClick={()=>load(cursor)}>Load more requests</button>}</section>
}
