import {strict as assert} from 'assert';
import request from 'supertest';
import {createApp} from '../../src/server/app';
import {DomainError} from '../../src/domain';
const actor={id:'owner',tenantId:'acme',roles:['requester']};
const config={origin:'http://localhost:4900',issuer:'http://localhost:4901/realms/switchboard',clientId:'switchboard',policy:{stages:['security','commercial'],approvalTimeoutMs:600000,reminderAfterMs:300000}};
const record={id:'req-1',workflowId:'flow-1',tenantId:'acme',requesterId:'owner',input:{customer:'Acme',plan:'standard',seats:3},createdAt:'2022-08-01T09:00:00Z',startedAt:null};
function fixture(overrides:any={}){
 const events:any[]=[];let identity:any=actor;
 const registry:any={pool:{query:async()=>({rows:[{ok:1}]})},admit:async(a:any,k:any,p:any)=>{events.push(['admit',a,k,p]);return record},markStarted:async()=>events.push(['started']),get:async()=>record,list:async()=>({items:[record],nextCursor:null})};
 const workflows:any={ready:async()=>{},start:async()=>events.push(['start']),query:async()=>({status:'pending',stage:'security',revision:0,receipts:[]}),decide:async(r:any,d:any)=>events.push(['decide',d]),cancel:async(r:any,a:any)=>events.push(['cancel',a])};
 const app=createApp({registry,workflows,config,authenticate:async(h:any)=>{if(!h)throw new DomainError('unauthorized','Sign in',401);return identity},...overrides});
 return {app,events,registry,workflows,setIdentity:(a:any)=>identity=a};
}
describe('approval HTTP API',()=>{
 it('separates health from dependency readiness',async()=>{const f=fixture();await request(f.app).get('/health').expect(200);await request(f.app).get('/ready').expect(200);f.workflows.ready=async()=>{throw new Error('internal address')};const r=await request(f.app).get('/ready').expect(503);assert.equal(JSON.stringify(r.body).includes('internal address'),false)});
 it('submits authenticated validated requests with idempotency keys',async()=>{const f=fixture();await request(f.app).post('/api/requests').send(record.input).expect(401);await request(f.app).post('/api/requests').set('Authorization','Bearer demo').send(record.input).expect(400);const r=await request(f.app).post('/api/requests').set('Authorization','Bearer demo').set('Idempotency-Key','key-1').send(record.input).expect(202);assert.equal(r.body.id,'req-1');assert.deepEqual(f.events.map(x=>x[0]),['admit','start','started']);f.setIdentity({...actor,roles:['security-reviewer']});await request(f.app).post('/api/requests').set('Authorization','Bearer demo').set('Idempotency-Key','key-2').send(record.input).expect(403)});
 it('uses registry visibility before reading workflow state',async()=>{const f=fixture();const r=await request(f.app).get('/api/requests/req-1').set('Authorization','Bearer demo').expect(200);assert.equal(r.body.status,'pending');f.registry.get=async()=>{throw new DomainError('not_found','Request not found',404)};await request(f.app).get('/api/requests/req-1').set('Authorization','Bearer demo').expect(404)});
 it('accepts decisions without claiming they are already applied',async()=>{const f=fixture();f.setIdentity({...actor,id:'reviewer',roles:['security-reviewer']});const body={id:'decision-1',stage:'security',choice:'approve',note:'Reviewed',revision:0};const r=await request(f.app).post('/api/requests/req-1/decisions').set('Authorization','Bearer demo').send(body).expect(202);assert.equal(r.body.status,'submitted');assert.equal(f.events[0][1].actor.id,'reviewer');await request(f.app).post('/api/requests/req-1/decisions').set('Authorization','Bearer demo').send({...body,actor:{id:'admin'}}).expect(400);await request(f.app).post('/api/requests/req-1/decisions').set('Authorization','Bearer demo').send({...body,stage:'commercial'}).expect(403)});
 it('permits cancellation only for the requester or an operator',async()=>{const f=fixture();await request(f.app).post('/api/requests/req-1/cancel').set('Authorization','Bearer demo').send({}).expect(202);f.setIdentity({...actor,id:'reviewer',roles:['security-reviewer']});await request(f.app).post('/api/requests/req-1/cancel').set('Authorization','Bearer demo').send({}).expect(403);f.setIdentity({...actor,id:'ops',roles:['operator']});await request(f.app).post('/api/requests/req-1/cancel').set('Authorization','Bearer demo').send({}).expect(202)});
 it('lists visible requests and marks unavailable workflow state',async()=>{const f=fixture();let r=await request(f.app).get('/api/requests?limit=10').set('Authorization','Bearer demo').expect(200);assert.equal(r.body.items[0].snapshot.status,'pending');f.workflows.query=async()=>{throw new Error('private host')};r=await request(f.app).get('/api/requests').set('Authorization','Bearer demo').expect(200);assert.equal(r.body.items[0].snapshot,null);assert.equal(r.body.items[0].stateUnavailable,true);await request(f.app).get('/api/requests?unknown=value').set('Authorization','Bearer demo').expect(400)});
 it('bounds body size and redacts unexpected failures',async()=>{const f=fixture();await request(f.app).post('/api/requests').set('Authorization','Bearer demo').set('Idempotency-Key','key-1').send({...record.input,customer:'a'.repeat(20000)}).expect(413);f.registry.admit=async()=>{throw new Error('postgres://private-password')};const r=await request(f.app).post('/api/requests').set('Authorization','Bearer demo').set('Idempotency-Key','key-2').send(record.input).expect(500);assert.equal(r.body.code,'internal_error');assert.ok(r.body.traceId);assert.equal(JSON.stringify(r.body).includes('password'),false)});
 it('rejects foreign origins and unexpected hostnames',async()=>{const f=fixture();await request(f.app).get('/health').set('Host','attacker.example').expect(400);await request(f.app).post('/api/requests').set('Origin','https://attacker.example').set('Authorization','Bearer demo').set('Idempotency-Key','key-1').send(record.input).expect(403);const r=await request(f.app).get('/health').expect(200);assert.equal(r.headers['x-content-type-options'],'nosniff');assert.ok(r.headers['content-security-policy'].includes("frame-ancestors 'none'"))});
 it('limits mutation attempts per identity and expires the budget',async()=>{let now=1000;const f=fixture({mutationBudget:1,now:()=>now});const send=()=>request(f.app).post('/api/requests').set('Authorization','Bearer demo').set('Idempotency-Key','key-1').send(record.input);await send().expect(202);const r=await send().expect(429);assert.ok(r.headers['retry-after']);now+=60001;await send().expect(202);await request(f.app).get('/api/session').set('Authorization','Bearer demo').expect(200)});
});
